#-*- coding:utf-8 -*-

from spell_dict import spell_dict

common_dict = {
    "Armor Class ": "Класс Доспеха ",
    "Hit Points ": "Хиты ",
    "Speed ": "Скорость ",
    "Armor Class: ": "Класс Доспеха ",
    "Hit Points: ": "Хиты ",
    "Speed: ": "Скорость ",
    "ft.": "фт.",
    "Saving Throws ": "Спасброски ",
    "Saving Throws: ": "Спасброски ",
    "fly": "полёт",
    "swim": "плавание",
    "burrow": "рытьё",
    "climb": "взбирание",
    "hover": "парение",
    "Special Senses ": "Чувства ",
    "Senses ": "Чувства ",
    "Senses: ": "Чувства ",
    " darkvision ": " тёмное зрение ",
    "passive ": "пассивное ",
    "Condition Immunities": "Иммунитет к состояниям",
    "Condition immunities": "Иммунитет к состояниям",
    "poisoned": "отравленный",
    "tremorsense": "чувство дрожи",
    "blindsight": "слепое зрение",
    "Challenge ": "Опасность ",
    " XP)": " опыта)",
    "Actions": "Действия",
    "ACTIONS": "Действия",
    "Multiattack.": "Мультиатака.",
    "one target": "одна цель",
    "Hit: ": "Попадание: ",
    "Melee Weapon Attack:": "Рукопашная атака оружием:",
    "Melee Weapon attack:": "Рукопашная атака оружием:",
    "Ranged Weapon Attack: ": "Дальнобойная атака оружием: ",
    "Ranged Weapon attack: ": "Дальнобойная атака оружием: ",
    "(Recharge": "(Перезарядка",
    "Damage Vulnerabilities ": "Уязвимость к урону ",
    "Melee Spell Attack:": "Рукопашная атака заклинанием:",
    "Ranged Spell Attack:": "Дальнобойная атака заклинанием:",
    " to hit, reach ": " к попаданию, досягаемость ",
    " to hit, range": " к попаданию, дистанция",
    "Cantrips": "Заговоры",
    "Cantrip": "Заговор",
    "at will": "неограниченно",
    "At will": "Неограниченно",
    "telepathy": "телепатия",
    "understands": "понимает",
    "but can't speak": "но не может говорить",
# параметры
    "STR": "СИЛ",
    "DEX": "ЛОВ",
    "CON": "ТЕЛ",
    "INT": "ИНТ",
    "WIS": "МДР",
    "CHA": "ХАР",
    "Str ": "Сил ",
    "Dex ": "Лов ",
    "Con ": "Тел ",
    "Int ": "Инт ",
    "Wis ": "Мдр ",
    "Cha ": "Хар ",
    "Strength": "Сила",
    "Dexterity": "Ловкость",
    "Constitution": "Телосложение",
    "Intelligence": "Интеллект",
    "Wisdom": "Мудрость",
    "Charisma": "Харизма",
}

damage_dict = {
# типы урона
    " lightning damage": " урон молнией",
    " damage ": " урон ",
    " damage.": " урон.",
    " damage,": " урон,",
    " plus ": " плюс ",
    " piercing": " колющий",
    " bludgeoning": " дробящий",
    " slashing": " рубящий",
    " fire": " огненный",
    " cold": " холод",
    " poison": " яд",
    " psychic": " психический",
    " acid": " кислотный",
    " lightning": " молния",
    " necrotic": " некротический",
    " radiant": " излучение",
    " force": "силовым полем",
}

alignment_dict = {
# мировоззрения
    "chaotic evil": "хаотично-злой",
    "lawful evil": "законно-злой",
    "neutral evil": "нейтрально-злой",
    "chaotic good": "хаотично-добрый",
    "lawful good": "законно-добрый",
    "neutral good": "нейтрально-добрый",
    "chaotic neutral": "хаотично-нейтральный",
    "lawful neutral": "законно-нейтральный",
    "neutral": "нейтральный",
    "unaligned": "без мировоззрения",
    "any non-good alignment": "любое не хорошее мировоззрение",
    "any good alignment": "любое хорошее мировоззрение",
}

armor_dict = {
    " shield": " щит",
    "scale armor": "чешуйчатый доспех",
    "scale mail": "чешуйчатый доспех",
    "natural armor": "естественный доспех",
    "with mage armor": "с магическим доспехом",
    "studded leather": "проклёпанный кожаный доспех",
    "Barkskin trait": "дубовая кора",
    "chain mail": "кольчуга",
    "chain shirt": "кольчужная рубаха",
    "ring mail": "колечный",
    "hide armor": "шкурный",
    "plate": "латы",
    "leather armor": "кожаный доспех",
}

creature_dict = {
# описания существ
    "Tiny": "Крошечный",
    "Small ": "Маленький ",
    "Medium": "Средний",
    "Large ": "Большой ",
    "Huge": "Огромный",
    "Gargantuan": "Громадный",
    "giant": "гигант",
    "humanoid": "гуманоид",
    "Humanoid": "Гуманоид",
    "kobold": "кобольд",
    "fiend": "изверг",
    "monstrosity": "чудовище",
    "Monstrosity": "чудовище",
    "undead": "нежить",
    "goblinoid": "гоблиноид",
    "elemental": "элементаль",
    "beast": "зверь",
    "demon": "демон",
    "ooze": "слизь",
    "construct": "конструкция",
    "devil": "дьявол",
    "dragon": "дракон",
    "aberration": "аберрация",
    "plant": "растение",
    "fey": "фей",
    "celestial": "небожитель",
    "Wight": "Умертвие",
    "Ghast": "Вурдалак",
    "Ghoul": "Упырь",
    "human": "человек",
    "shapechanger": "перевёртыш",
    "Weretiger": "Вертигр",
}

weapon_dict = {
# weapon
    "Battleaxe": "Боевой топор",
    "Blowgun": "Духовая трубка",
    "Club": "Дубинка",
    "Crossbow, hand": "Арбалет, ручной",
    "Crossbow, heavy": "Арбалет, тяжёлый",
    "Crossbow, light": "Арбалет, лёгкий",
    "Dagger": "Кинжал",
    "Dart": "Дротик",
    "Flail": "Цеп",
    "Glaive": "Глефа",
    "Greataxe": "Секира",
    "Greatclub": "Палица",
    "Greatsword": "Двуручный меч",
    "Halberd": "Алебарда",
    "Handaxe": "Ручной топор",
    "Javelin": "Метательное копьё",
    "Lance": "Длинное копьё",
    "Light hammer": "Лёгкий молот",
    "Longbow": "Длинный лук",
    "Longsword": "Длинный меч",
    "Light Crossbow": "Лёгкий арбалет",
    "Mace": "Булава",
    "Maul": "Молот",
    "Morningstar": "Моргенштерн",
    "Net": "Сеть",
    "Pike": "Пика",
    "Quarterstaff": "Боевой посох",
    "Rapier": "Рапира",
    "Scimitar": "Скимитар",
    "Shortbow": "Короткий лук",
    "Short Bow": "Короткий лук",
    "Shortsword": "Короткий меч",
    "Short Sword": "Короткий меч",
    "Sickle": "Серп",
    "Sling": "Праща",
    "Spear": "Копьё",
    "Trident": "Трезубец",
    "War pick": "Боевая кирка",
    "Warhammer": "Боевой молот",
    "Whip": "Кнут",
    "Rock": "Камень",
    "rock": "камень",
    "Bite": "Укус",
    "bite": "укус",
    "Beak": "Клюв",
    "beak": "клюв",
    "Claw": "Когти",
    "claw": "когти",
    "Gore": "Бодание",
    "Tail": "Хвост",
    "Tentacles": "Щупальца",
    "Hooves": "Копыта",
    "Stinger": "Жало",
    "Swallow": "Проглатывание",
    "Fling": "Бросок",
    "Thorn": "Шип",
    "Tentacle": "Щупальца",
}

lang_dict = {
    "Languages ": "Языки ",
    "Languages: ": "Языки ",
    "Common": "Общий",
    "Elvish": "Эльфийский",
    "Dwarwish": "Дварфийский",
    "Giant": "Язык гигантов",
    "Ignan": "Игнан",
    "Bothii": "Ботхи",
    "Yikaria ": "Икария",
    "Draconic": "Драконий",
    "Goblin": "Гоблинский",
    "Orc": "Орочий",
    "Undercommon": "Подземный",
    "Telepathy": "Телепатия",
    "Abyssal": "Бездны",
}

condition_dict = {
    "": "",
    "Blinded": "Ослеплённый",
    "blinded": "Ослеплённый",
    "charmed": "Очарованный",
    "Charmed": "Очарованный",
    "Deafened": "Оглохший",
    "deafened": "Оглохший",
    "Frightened": "Испуганный",
    "frightened": "Испуганный",
    "Grappled": "Схваченный",
    "grappled": "Схваченный",
    "Incapacitated": "Недееспособный",
    "incapacitated": "Недееспособный",
    "Invisible": "Невидимый",
    "invisible": "Невидимый",
    "Paralyzed": "Парализованный",
    "paralyzed": "Парализованный",
    "Petrified": "Окаменевший",
    "petrified": "Окаменевший",
    "Poisoned": "Отравленный",
    "poisoned": "Отравленный",
    "Prone": "Лежащий ничком",
    "prone": "Лежащий ничком",
    "Restrained": "Удерживаемый",
    "restrained": "Удерживаемый",
    "Stunned": "Ошеломлённый",
    "stunned": "Ошеломлённый",
    "Unconscious": "Бессознательный",
    "unconscious": "Бессознательный",
}

skill_dict = {
    "Skills ": "Навыки ",
    "Skills: ": "Навыки ",
    "Acrobatics ": "Акробатика ",
    "Animal Handling ": "Уход за животными ",
    "Arcana ": "Магия ",
    "Athletics ": "Атлетика ",
    "Deception ": "Обман ",
    "History ": "История ",
    "Insight ": "Проницательность ",
    "Intimidation ": "Запугивание ",
    "Investigation ": "Расследование ",
    "Medicine ": "Медицина",
    "Nature": "Природа",
    "Perception": "Восприятие",
    "Performance ": "Выступление ",
    "Persuasion ": "Убеждение ",
    "Religion ": "Религия ",
    "Sleight of Hand ": "Ловкость рук ",
    "Stealth ": "Скрытность ",
    "Survival ": "Выживание ",
}

race_dict = {
    "Aasimar": "Аасимар",
    "Half-Elf": "Полуэльф",
    " Elf ": " Эльф ",
}

abilities_dict = {
    "can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check":
        "может карабкаться по сложным поверхностям, включая вверх ногами по потолку, без необходимости проходить какие-то проверки",
    "Sunlight Sensitivity": "Чувствительность к солнечном свету",
    "Sunlight Hypersensitivity": "Гиперчувствительность к солнечном свету",
    "While in sunlight,": "Находясь на солнечном свету,",
    "has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.":
        "получает помеху на броски атак и на проверки Мудрости (Восприятия) основанные на зрении.",
    "Undead Fortitude": "Стойкость Нежити",
    "If damage reduces": "Если урон понижает хиты",
    "it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success,":
        "он должен пройти спасбросок Телосложения против Сл 5 + полученный урон, если только урон не от сияния или критического попадания. При успехе хиты",
    "drops to 1 hit point instead": "вместо этого снижаются до 1",
    "Undead Nature": "Природа нежити",
    "Ooze Nature": "Природа слизи",
    "doesn't require air food, drink, or sleep": "не нужно дышать, есть, пить или спать",
    "doesn't require air or sleep": "не нужно дышать или спать",
    "doesn't require sleep": "не нужно спать",
    "Amphibious": "Амфибия",
    "can breathe air and water": "может дышать и воздухом и под водой",
    "Magic Resistance. ": "Сопротивление магии. ",
    "Damage Immunities ": "Иммунитет к урону ",
    "Damage Resistances ": "Сопротивление к урону ",
    "Damage Immunities: ": "Иммунитет к урону ",
    "Damage Resistances: ": "Сопротивление к урону ",
    "has advantage on saving throws against spells and other magical effects": "получает преимущество на спасброски против заклинаний и прочих магических эффектов",
    "spell save DC": "Сл спасброска от заклинания",
    "slots": "ячейки",
    "slot": "ячейка",
    "level": "уровень",
    "Level": "уровень",
    "1st": "1-й",
    "2nd": "2-й",
    "3rd": "3-й",
    "4th": "4-й",
    "5th": "5-й",
    "6th": "6-й",
    "7th": "7-й",
    "8th": "8-й",
    "9th": "9-й",
    "Spellcasting": "Колдовство",
    "Special Equipment": "Специальное снаряжение",
    "/day each": "/день каждое",
    "The attack deals an extra": "Атака причиняет дополнительный урон",
    "has advantage on the attack roll": " обладая преимуществом при броске атаки",
    "on a failed save": "при провале",
    "or half as much damage on a successful one": "или половину этого урона при успехе",
    "taking": "получая",
    "Regeneration": "Регенерация",
    "Reactions": "Реакции",
    "Spell Reflection": "Отражение заклинаний",
    "Lair Actions": "Действия логова",
    "Trampling Charge": "Растаптывающий рывок",
    "Petrifying Breath": "Окаменяющее дыхание",
    "one creature": "одно существо",
    "Cunning Action": "Хитрое действие",
    "Duergar Resilience": "Дуэргарская устойчивость",
    "Enlarge": "Увеличение",
    "Water Breathing": "Подводное дыхание",
    "can breathe only underwater": "может дышать только под водой",
    "Turn Immunity": "Иммунитет к изгнанию",
    "is immune to effects that turn undead": "обладает иммунитетом к эффектам, изгоняющим нежить",
    "escape DC": "Сл высвобождения",
    "Until this grapple ends, the target is": "Пока цель схвачена, она",
    "another target": "другую цель",
    "and the target is grappled": "и цель Схвачена",
    "(self only)": "(только на себя)",
    "Standing Leap": "Прыжок с места",
    "Life Drain": "Вытягивание жизни",
    "Evasion": "Уклонение",
    "Sneak Attack": "Скрытая атака",
    "Assassinate": "Убийство",
    "Turn Resistance": "Сопротивление изгнанию",
    "has advantage on saving throws against any effect that turns undead": "совершает с преимуществом спасброски от всех эффектов, изгоняющих нежить",
    "Slam": "Размашистый удар",
    "False Appearance": "Обманчивая внешность",
    "Speak with Animals": "Разговор с животными",
    "Pseudopod": "Ложноножка",
    "if used with two hands": "при ударе двумя руками",
    "Amorphous Form": "Аморфная форма",
    "Corrode Metal": "Коррозия металла",
    "Killer Response": "Реакция убийцы",
    "Siege Monster": "Осадное Чудовище",
    "deals double damage to objects and structures": "наносит двойное повреждение объектам и строениям",
    "Clouring": "Излучение",
    "Flexible": "Гибкость",
    "Blood Sense": "Чувство крови",
    "Forbiddance": "Запрет",
    "Misty Form": "Туманная форма",
    "Blood Drain": "Высасывание крови",
    "Blinding Acid": "Ослепляющая кислота",
    "Protection": "Защита",
    "Spit Acid": "Плевок кислоты",
    "Stupefying Touch": "Ошеломляющее прикосновение",
    "Focused Conjuration": "Фокусировка на школе Вызова",
    "Rejuvenation": "Восстановление",
    "Paralyzing Touch": "Парализующее касание",
    "Benign Transposition": "Добровольная перестановка",
    "": "",
    "": "",
    "": "",
}

name_dict = {
    "Wight": "Умертвие",
    "Spy": "Шпион",
    "Assassin": "Наёмный убийца",
    "Tecuziztecatl": "Текузизтекатль",
    "Sharwyn": "Шарвин",
    "The kraken": "Кракен",
    "": "",
    "Abjuration": "Ограждение",
    "Conjuration": "Вызов",
    "Divination": "Прорицание",
    "Enchantment": "Очарование",
    "Evocation": "Воплощение",
    "Illusion": "Иллюзия",
    "Necromancy": "Некромантия",
    "Transmutation": "Преобразование",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "barbarian": "варвар",
    "bard": "бард",
    "cleric": "жрец",
    "druid": "друид",
    "fighter": "воин",
    "monk": "монах",
    "paladin": "паладиин",
    "ranger": "следопыт",
    "rogue": "плут",
    "sorcerer": "чародей",
    "warlock": "колдун",
    "wizard": "волшебник",
}



item_dict = {**weapon_dict, **armor_dict}

# В all_dict не включается lang_dict т.к. тогда поедут названия монстров типа Goblin, Orc
all_dict = {**abilities_dict, **spell_dict, **common_dict, **skill_dict, **condition_dict, **item_dict,
    **alignment_dict, **creature_dict, **damage_dict, **race_dict, **name_dict}
