#-*- coding:utf-8 -*-

abilities_dict = {
    "can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check":
        "может карабкаться по сложным поверхностям, включая вверх ногами по потолку, без необходимости проходить какие-то проверки",
    "Sunlight Sensitivity": "Чувствительность к солнечном свету",
    "Sunlight Hypersensitivity": "Гиперчувствительность к солнечном свету",
    "While in sunlight,": "Находясь на солнечном свету,",
    "has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.":
        "получает помеху на броски атак и на проверки Мудрости (Восприятия) основанные на зрении.",
    "Undead Fortitude": "Стойкость Нежити",
    "If damage reduces": "Если урон понижает хиты",
    "it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success,":
        "он должен пройти спасбросок Телосложения против Сл 5 + полученный урон, если только урон не от сияния или критического попадания. При успехе хиты",
    "drops to 1 hit point instead": "вместо этого снижаются до 1",
    "Undead Nature": "Природа нежити",
    "Ooze Nature": "Природа слизи",
    "doesn't require air food, drink, or sleep": "не нужно дышать, есть, пить или спать",
    "doesn't require air or sleep": "не нужно дышать или спать",
    "doesn't require sleep": "не нужно спать",
    "Amphibious": "Амфибия",
    "can breathe air and water": "может дышать и воздухом и под водой",
    "Magic Resistance": "Сопротивление магии",
    "Magic Weapons": "Магическое оружие",
    "Damage Immunities ": "Иммунитет к урону ",
    "Damage Resistances ": "Сопротивление к урону ",
    "Damage Immunities: ": "Иммунитет к урону ",
    "Damage Resistances: ": "Сопротивление к урону ",
    "has advantage on saving throws against spells and other magical effects": "получает преимущество на спасброски против заклинаний и прочих магических эффектов",
    "spell save DC": "Сл спасброска от заклинания",
    "slots": "ячейки",
    "slot": "ячейка",
    "level": "уровень",
    "Level": "уровень",
    "1st": "1-й",
    "2nd": "2-й",
    "3rd": "3-й",
    "4th": "4-й",
    "5th": "5-й",
    "6th": "6-й",
    "7th": "7-й",
    "8th": "8-й",
    "9th": "9-й",
    "Innate Spellcasting": "Врождённое колдовство",
    "Spellcasting": "Колдовство",
    "Limited Magic Immunity": "Ограниченный иммунитет к магии",
    "Magic Immunity": "Иммунитет к магии",
    "Special Equipment": "Специальное снаряжение",
    "/day each": "/день каждое",
    "The attack deals an extra": "Атака причиняет дополнительный урон",
    "has advantage on the attack roll": " обладая преимуществом при броске атаки",
    "on a failed save": "при провале",
    "or half as much damage on a successful one": "или половину этого урона при успехе",
    "taking": "получая",
    "Regeneration": "Регенерация",
    "Reactions": "Реакции",
    "Spell Reflection": "Отражение заклинаний",
    "Lair Actions": "Действия логова",
    "Trampling Charge": "Растаптывающий рывок",
    "Petrifying Breath": "Окаменяющее дыхание",
    "one creature": "одно существо",
    "Cunning Action": "Хитрое действие",
    "Duergar Resilience": "Дуэргарская устойчивость",
    "Enlarge": "Увеличение",
    "Water Breathing": "Подводное дыхание",
    "can breathe only underwater": "может дышать только под водой",
    "Turn Immunity": "Иммунитет к изгнанию",
    "is immune to effects that turn undead": "обладает иммунитетом к эффектам, изгоняющим нежить",
    "escape DC": "Сл высвобождения",
    "Until this grapple ends, the target is": "Пока цель схвачена, она",
    "another target": "другую цель",
    "and the target is grappled": "и цель Схвачена",
    "(self only)": "(только на себя)",
    "Standing Leap": "Прыжок с места",
    "Life Drain": "Вытягивание жизни",
    "Evasion": "Уклонение",
    "Sneak Attack": "Скрытая атака",
    "Assassinate": "Убийство",
    "Turn Resistance": "Сопротивление изгнанию",
    "has advantage on saving throws against any effect that turns undead": "совершает с преимуществом спасброски от всех эффектов, изгоняющих нежить",
    "Slam": "Размашистый удар",
    "False Appearance": "Обманчивая внешность",
    "Speak with Animals": "Разговор с животными",
    "Pseudopod": "Ложноножка",
    "if used with two hands": "при ударе двумя руками",
    "Amorphous Form": "Аморфная форма",
    "Corrode Metal": "Коррозия металла",
    "Killer Response": "Реакция убийцы",
    "Siege Monster": "Осадное Чудовище",
    "deals double damage to objects and structures": "наносит двойное повреждение объектам и строениям",
    "Clouring": "Излучение",
    "Flexible": "Гибкость",
    "Blood Sense": "Чувство крови",
    "Forbiddance": "Запрет",
    "Misty Form": "Туманная форма",
    "Blood Drain": "Высасывание крови",
    "Blinding Acid": "Ослепляющая кислота",
    "Protection": "Защита",
    "Spit Acid": "Плевок кислоты",
    "Stupefying Touch": "Ошеломляющее прикосновение",
    "Focused Conjuration": "Фокусировка на школе Вызова",
    "Rejuvenation": "Восстановление",
    "Paralyzing Touch": "Парализующее касание",
    "Benign Transposition": "Добровольная перестановка",
    "Charge": "Рывок",
    "": "",
    "": "",
}
