#-*- coding:utf-8 -*-

creature_dict = {
# описания существ
    "Tiny": "Крошечный",
    "Small ": "Маленький ",
    "Medium": "Средний",
    "Large ": "Большой ",
    "Huge": "Огромный",
    "Gargantuan": "Громадный",
    "giant": "гигант",
    "humanoid": "гуманоид",
    "Humanoid": "Гуманоид",
    "kobold": "кобольд",
    "fiend": "изверг",
    "monstrosity": "чудовище",
    "Monstrosity": "чудовище",
    "undead": "нежить",
    "goblinoid": "гоблиноид",
    "elemental": "элементаль",
    "beast": "зверь",
    "demon": "демон",
    "ooze": "слизь",
    "construct": "констракт",
    "devil": "дьявол",
    "dragon": "дракон",
    "aberration": "аберрация",
    "plant": "растение",
    "fey": "фей",
    "celestial": "небожитель",
    "Wight": "Умертвие",
    "Ghast": "Вурдалак",
    "Ghoul": "Упырь",
    "human": "человек",
    "shapechanger": "перевёртыш",
    "Weretiger": "Вертигр",
}
