#-*- coding:utf-8 -*-

weapon_dict = {
    "Battleaxe": "Боевой топор",
    "Blowgun": "Духовая трубка",
    "Club": "Дубинка",
    "Crossbow, hand": "Арбалет, ручной",
    "Crossbow, heavy": "Арбалет, тяжёлый",
    "Crossbow, light": "Арбалет, лёгкий",
    "Dagger": "Кинжал",
    "Dart": "Дротик",
    "Flail": "Цеп",
    "Glaive": "Глефа",
    "Greataxe": "Секира",
    "Greatclub": "Палица",
    "Greatsword": "Двуручный меч",
    "Halberd": "Алебарда",
    "Handaxe": "Ручной топор",
    "Javelin": "Метательное копьё",
    "Lance": "Длинное копьё",
    "Light hammer": "Лёгкий молот",
    "Longbow": "Длинный лук",
    "Longsword": "Длинный меч",
    "Light Crossbow": "Лёгкий арбалет",
    "Mace": "Булава",
    "Maul": "Молот",
    "Morningstar": "Моргенштерн",
    "Net": "Сеть",
    "Pike": "Пика",
    "Quarterstaff": "Боевой посох",
    "Rapier": "Рапира",
    "Scimitar": "Скимитар",
    "Shortbow": "Короткий лук",
    "Short Bow": "Короткий лук",
    "Shortsword": "Короткий меч",
    "Short Sword": "Короткий меч",
    "Sickle": "Серп",
    "Sling": "Праща",
    "Spear": "Копьё",
    "Trident": "Трезубец",
    "War pick": "Боевая кирка",
    "Warhammer": "Боевой молот",
    "Whip": "Кнут",
    ### Абилки монстров
    "Rock": "Камень",
    "rock": "камень",
    "Bite": "Укус",
    "bite": "укус",
    "Beak": "Клюв",
    "beak": "клюв",
    "Claw": "Когти",
    "claw": "когти",
    "Gore": "Бодание",
    "Tail": "Хвост",
    "Horn": "Рог",
    "Tentacles": "Щупальца",
    "Hooves": "Копыта",
    "Stinger": "Жало",
    "Swallow": "Проглатывание",
    "Fling": "Бросок",
    "Thorn": "Шип",
    "Tentacle": "Щупальца",
    "Branch": "Ветвь",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

armor_dict = {
    " shield": " щит",
    "scale armor": "чешуйчатый доспех",
    "scale mail": "чешуйчатый доспех",
    "natural armor": "естественный доспех",
    "with mage armor": "с магическим доспехом",
    "studded leather": "проклёпанный кожаный доспех",
    "Barkskin trait": "дубовая кора",
    "chain mail": "кольчуга",
    "chain shirt": "кольчужная рубаха",
    "ring mail": "колечный",
    "ring mail armor": "колечный доспех",
    "hide armor": "шкурный доспех",
    "plate": "латы",
    "leather armor": "кожаный доспех",
    "breastplate": "кираса",
    "half plate armor": "полулаты",
    "padded armor": "стёганный доспех",
    "plate armor": "латы",
    "splint armor": "наборный доспех",
    "": "",
}
