# -*- coding:utf-8 -*-

weapon_dict = {
    "Battleaxe": "Боевой топор",
    "Blowgun": "Духовая трубка",
    "Club": "Дубинка",
    "Crossbow, hand": "Арбалет, ручной",
    "Crossbow, heavy": "Арбалет, тяжёлый",
    "Crossbow, light": "Арбалет, лёгкий",
    "Dagger": "Кинжал",
    "Dart": "Дротик",
    "Flail": "Цеп",
    "Glaive": "Глефа",
    "Greataxe": "Секира",
    "Greatclub": "Палица",
    "Greatsword": "Двуручный меч",
    "Halberd": "Алебарда",
    "Handaxe": "Ручной топор",
    "Javelin": "Метательное копьё",
    "Lance": "Длинное копьё",
    "Light hammer": "Лёгкий молот",
    "Longbow": "Длинный лук",
    "Longsword": "Длинный меч",
    "Light Crossbow": "Лёгкий арбалет",
    "Mace": "Булава",
    "Maul": "Молот",
    "Morningstar": "Моргенштерн",
    "Net": "Сеть",
    "Pike": "Пика",
    "Quarterstaff": "Боевой посох",
    "Rapier": "Рапира",
    "Scimitar": "Скимитар",
    "Shortbow": "Короткий лук",
    "Short Bow": "Короткий лук",
    "Shortsword": "Короткий меч",
    "Short Sword": "Короткий меч",
    "Sickle": "Серп",
    "Sling": "Праща",
    "Spear": "Копьё",
    "Trident": "Трезубец",
    "War pick": "Боевая кирка",
    "Warhammer": "Боевой молот",
    "Whip": "Кнут",
    # Абилки монстров
    "Rock": "Камень",
    "rock": "камень",
    "Bite": "Укус",
    "bite": "укус",
    "Beak": "Клюв",
    "beak": "клюв",
    "Claws": "Когти",
    "claws": "Когти",
    "Claw": "Когти",
    "claw": "когти",
    "Gore": "Бодание",
    "Tail": "Хвост",
    "Horn": "Рог",
    "Tentacles": "Щупальца",
    "Hooves": "Копыта",
    "Stinger": "Жало",
    "Swallow": "Проглатывание",
    "Fling": "Бросок",
    "Thorn": "Шип",
    "Tentacle": "Щупальца",
    "Branch": "Ветвь",
    "Slam": "Удар",
    "": "",
}

armor_dict = {
    " shield": " щит",
    "scale armor": "чешуйчатый доспех",
    "scale mail": "чешуйчатый доспех",
    "natural armor": "природный доспех",
    "with mage armor": "с магическим доспехом",
    "studded leather": "проклёпанный кожаный доспех",
    "Barkskin trait": "дубовая кора",
    "chain mail": "кольчуга",
    "chain shirt": "кольчужная рубаха",
    "ring mail": "колечный",
    "ring mail armor": "колечный доспех",
    "hide armor": "шкурный доспех",
    "breastplate": "кираса",
    "plate": "латы",
    "leather armor": "кожаный доспех",
    "half plate armor": "полулаты",
    "padded armor": "стёганный доспех",
    "plate armor": "латы",
    "splint armor": "наборный доспех",
    "": "",
}

equipment_packs_dict = {
    "burglar's pack": "набор взломщика",
    "diplomat's pack": "набор дипломата",
    "dungeoneer's pack": "набор исследователя под-земелий",
    "entertainer's pack": "набор артиста",
    "explorer's pack": "набор путешественника",
    "priest's pack": "набор священника",
    "scholar's pack": "набор учёного",
}

tools_dict = {
    "alchemist's supplies": "инструменты алхимика",
    "bagpipes": "волынка",
    "brewer's supplies": "инструменты пивовара",
    "calligrapher's supplies": "инструменты каллиграфа",
    "carpenter's tools": "инструменты плотника",
    "cartographer's tools": "инструменты картографа",
    "cobbler's tools": "инструменты сапожника",
    "cook's utensils": "инструменты повара",
    "dice set": "кости",
    "disguise kit": "набор для грима",
    "dragonchess set": "драконьи шахматы",
    "drum": "барабан",
    "dulcimer": "цимбалы",
    "flute": "флейта",
    "forgery kit": "набор для фальсификации",
    "glassblower's tools": "инструменты стеклодува",
    "herbalism kit": "набор травника",
    "horn": "рожок",
    "jeweler's tools": "инструменты ювелира",
    "leatherworker's tools": "инструменты кожевника",
    "lute": "лютня",
    "lyre": "лира",
    "mason's tools": "инструменты каменщика",
    "navigator's tools": "инструменты навигатора",
    "painter's supplies": "инструменты художника",
    "pan flute": "свирель",
    "playing card set": "карты",
    "poisoner's kit": "инструменты отравителя",
    "potter's tools": "инструменты гончара",
    "shawm": "шалмей",
    "smith's tools": "инструменты кузнеца",
    "thieves' tools": "воровские инструменты",
    "three–dragon ante set": "ставка трех драконов",
    "tinker's tools": "инструменты жестянщика",
    "vehicles (land ar water)": "транспорт (наземный или водный)",
    "viol": "виола",
    "weaver's tools": "инструменты ткача",
    "woodcarver's tools": "инструменты резчика по дереву",
}

mounts_vehicles_dict = {
    "mounts and other animals": "скакуны и другие животные",
    "camel": "верблюд",
    "donkey or mule": "осёл или мул",
    "elephanl": "слон",
    "horse, drafl": "лошадь, тягловая",
    "horse, riding": "лошадь, ездовая",
    "masliff": "мастифф",
    "pony": "пони",
    "warhorse": "боевой конь",
    "tack, harness, ano drawn vehicles": "сёдла, упряжь и транспорт",
    "barding": "доспех",
    "bil and bridle": "упряжь и уздечка",
    "carriage": "коляска",
    "cart": "телега",
    "chariol": "карета",
    "feed": "корм",
    "saddiebags": "седельные сумки",
    "saddle exolic": "седло экзотическое",
    "saddle mililary": "седло военное",
    "saddle pack": "седло грузовое",
    "saddle riding": "седло ездовое",
    "slabling": "конюшня",
    "sled": "сани",
    "wagon": "фургон",
    "waterborne vehicles": "водный транспорт",
    "galley": "галера",
    "keelboal": "килевая лодка",
    "longship": "драккар",
    "rowboal": "шлюпка",
    "sailing ship": "парусник",
    "warship": "военный корабль",
    "punt": "струг",
    "great ship": "ладья",
}

adventuring_gear_dict = {
    "adventuring gear": "снаряжение",
    "abacus": "абак",
    "acid (vial)": "кислота (флакон)",
    "alchemist’s fire (flask)": "алхимический огонь (фляга)",
    "ammunition": "боеприпасы",
    "blowgun needles": "иглы для трубки",
    "crossbow bolts": "арбалетные болты",
    "sling bullets": "снаряды для пращи",
    "antitoxin (vial)": "противоядие (флакон)",
    "arcane focus": "магическая фокусировка",
    "crystal": "кристалл",
    "orb": "сфера",
    "rod": "жезл",
    "staff": "посох",
    "wand": "волшебная палочка",
    "arrows": "стрелы",
    "backpack": "рюкзак",
    "ball bearings": "металлические шарики",
    "barrel": "бочка",
    "basket": "корзина",
    "bedroll": "спальник",
    "bell": "колокольчик",
    "blanket": "одеяло",
    "block and tackle": "блок и лебёдка",
    "book": "книга",
    "bottle, glass": "бутылка, стеклянная",
    "bucket": "ведро",
    "caltrops": "калтропы",
    "candle": "свеча",
    "case, crossbow bolt": "контейнер для арбалетных болтов",
    "case, map or scroll": "контейнер для карт и свитков",
    "chain": "цепь",
    "chalk": "мел",
    "chest": "сундук",
    "climber's kit": "комплект для лазания",
    "clothes, common": "одежда, обычная",
    "clothes, costume": "одежда, костюм",
    "clothes, fine": "одежда, отличная",
    "clothes, traveler’s": "одежда, дорожная",
    "component pouch": "мешочек с компонентами",
    "crowbar": "ломик",
    "druidic focus": "фокусировка друидов",
    "sprig of mistletoe": "веточка омелы",
    "totem": "тотем",
    "wooden staff": "деревянный посох",
    "yew wand": "тисовая палочка",
    "fishing tackle": "комплект для рыбалки",
    "flask or tankard": "фляга или большая кружка",
    "grappling hook": "крюк-кошка",
    "hammer": "молоток",
    "hammer, sledge": "молот, кузнечный",
    "healer's kit": "комплект целителя",
    "holy symbol": "священный символ",
    "amulet": "амулет",
    "emblem": "эмблема",
    "reliquary": "реликварий",
    "holy water": "святая вода",
    "hourglass": "песочные часы",
    "hunting trap": "охотничий капкан",
    "ink": "чернила",
    "ink pen": "писчее перо",
    "jug or pitcher": "кувшин или графин",
    "ladder": "лестница",
    "lamp": "лампа",
    "lantern, bullseye": "фонарь, направленный",
    "lantern, hooded": "фонарь, закрытый",
    "lock": "замок",
    "magnifying glass": "увеличительное стекло",
    "manacles": "кандалы",
    "mess kit": "столовый набор",
    "mirror, steel": "зеркало, стальное",
    "oil": "масло (фляга)",
    "paper": "бумага",
    "parchment": "пергамент",
    "perfume": "духи",
    "pick, miner’s": "кирка, горняцкая",
    "piton": "шлямбур",
    "poison, basic": "яд, простой",
    "pole": "шест",
    "pot, iron": "горшок, железный",
    "potion of healing": "зелье лечения",
    "pouch": "кошель",
    "quiver": "колчан",
    "ram, portable": "таран, портативный",
    "rations": "рационы",
    "robes": "ряса",
    "rope, hempen": "верёвка пеньковая",
    "rope, silk": "верёвка, шёлковая",
    "sack": "мешок",
    "scale, merchant’s": "весы, торговые",
    "sealing wax": "воск",
    "shovel": "лопата",
    "signal whistle": "сигнальный свисток",
    "signet ring": "кольцо-печатка",
    "soap": "мыло",
    "spellbook": "книга заклинаний",
    "spikes, iron": "шипы, железные",
    "spyglass": "подзорная труба",
    "tent, two-person": "палатка, двухместная",
    "tinderbox": "трутница",
    "torch": "факел",
    "vial": "флакон",
    "waterskin": "бурдюк ",
    "whetstone": "точильный камень",
}

