# -*- coding:utf-8 -*-

common_name_dict = {
    "Wight": "Умертвие",
    "Spy": "Шпион",
    "Assassin": "Наёмный убийца",
    "Tecuziztecatl": "Текузизтекатль",
    "Sharwyn": "Шарвин",
    "The kraken": "Кракен",
    "Abjuration": "Ограждение",
    "Conjuration": "Вызов",
    "Divination": "Прорицание",
    "Enchantment": "Очарование",
    "Evocation": "Воплощение",
    "Illusion": "Иллюзия",
    "Necromancy": "Некромантия",
    "Transmutation": "Преобразование",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "barbarian": "варвар",
    "bard": "бард",
    "cleric": "жрец",
    "druid": "друид",
    "fighter": "воин",
    "monk": "монах",
    "paladin": "паладиин",
    "ranger": "следопыт",
    "rogue": "плут",
    "sorcerer": "чародей",
    "warlock": "колдун",
    "wizard": "волшебник",
}

volo_names_dict = {
    'Abjurer': 'Оградитель',
    'Alhoon': 'Алхун',
    'Annis Hag': 'Карга Аннис',
    'Apprentice Wizard': 'Ученик Волшебника',
    'Archdruid': 'Архидруид',
    'Archer': 'Лучник',
    'Aurochs': 'Тур',
    'Babau': 'Бабау',
    'Banderhobb': 'Бандерхобб',
    'Bard': 'Бард',
    'Barghest': 'Баргест',
    'Bheur Hag': 'Карга Бйор',
    'Blackguard': 'Темный Страж',
    'Bodak': 'Бодак',
    'Boggle': 'Боггл',
    'Brontosaurus': 'Бронтозавр',
    'Catoblepas': 'Катоблепас',
    'Cave Fisher': 'Пещерный Удильщик',
    'Champion': 'Чемпион',
    'Chitine': 'Хитин',
    'Choldrith': 'Холдрит',
    'Cloud Giant Smiling One': 'Облачный Гигант Насмешник',
    'Conjurer': 'Призыватель',
    'Cow': 'Корова',
    'Cranium Rat': 'Черепная Крыса',
    'Darkling': 'Дарклинг',
    'Darkling Elder': 'Старейшина Дарклингов',
    'Death Kiss': 'Поцелуй Смерти',
    'Deep Scion': 'Глубинный Отпрыск',
    'Deinonychus': 'Дейноних',
    'Devourer': 'Пожиратель',
    'Dimetrodon': 'Диметродон',
    'Diviner': 'Прорицатель',
    'Dolphin': 'Дельфин',
    'Draegloth': 'Дрэглот',
    'Elder Brain': 'Старший Мозг',
    'Enchanter': 'Очарователь',
    'Evoker': 'Воплотитель',
    'Fire Giant Dreadnought': 'Огненный Гигант Дредноут',
    'Firenewt': 'Огненный Тритон',
    'Firenewt Warlock Of Lmix': 'Огненный Тритон Колдун Имикса',
    'Flail Snail': 'Цеповая Улитка',
    'Flind': 'Флинд',
    'Froghemoth': 'Лягемот',
    'Frost Giant Everlasting One': 'Морозный Гигант Извечный',
    'Gauth': 'Гаут',
    'Gazer': 'Зрящий',
    'Giant Strider': 'Гигантский Ходун',
    'Girallon': 'Гираллон',
    'Gnoll Flesh Gnawer': 'Гнолл Глодатель',
    'Gnoll Hunter': 'Гнолл Охотник',
    'Gnoll Witherling': 'Иссохший Гнолл',
    'Grung': 'Грунг',
    'Grung Elite Warrior': 'Элитный Воин Грунг',
    'Grung Wildling': 'Одичавший Грунг',
    'Guard Drake': 'Сторожевой Дрейк',
    'Hadrosaurus': 'Гадрозавр',
    'Hobgoblin Devastator': 'Хобгоблин-Опустошитель',
    'Hobgoblin Iron Shadow': 'Хобгоблин Железная Тень',
    'Illusionist': 'Иллюзионист',
    'Ki-Rin': 'Ки-Рин',
    'Kobold Dragonshield': 'Кобольд Драконий Щит',
    'Kobold Inventor': 'Кобольд Изобретатель',
    'Kobold Scale Sorcerer': 'Кобольд Чешуйчатый Чародей',
    'Korred': 'Корред',
    'Kraken Priest': 'Священник Кракена',
    'Leucrotta': 'Лекротта',
    'Martial Arts Adept': 'Адепт Боевых Искусств',
    'Master Thief': 'Мастер-Вор',
    'Maw Demon': 'Утробный Демон',
    'Meenlock': 'Минлок',
    'Mind Flayer Lich': 'Свежеватель Разума Лич',
    'Mindwitness': 'Свидетель Разума',
    'Morkoth': 'Моркот',
    'Mouth Of Grolantor': 'Пасть Гролатора',
    'Necromancer': 'Некромант',
    'Neogi': 'Неоги',
    'Neogi Hatchling': 'Неоги Личинка',
    'Neogi Master': 'Повелитель Неоги',
    'Neothelid': 'Неотелид',
    'Nilbog': 'Нилбог',
    'Ore Blade Of Ilneval': 'Орк Клиное Илневала',
    'Ore Claw Of Luthic': 'Орк Коготь Лутик',
    'Ore Hand Ofyurtrus': 'Орк Рука Юртруса',
    'Ore Nurtured One Ofyurtrus': 'Орк Вскормленный Юртруса',
    'Ore Red Fang Of Shargaas': 'Орк Красный Клык Шаргааса',
    'Ox (Cow)': 'Як (Корова)',
    'Quetzalcoatlus': 'Кетцалькоатль',
    'Quickling': 'Квиклинг',
    'Redcap': 'Красный Колпак',
    'Rothe (Cow)': 'Роф (Корова)',
    'Sea Spawn-': 'Морское Отродье',
    'Shadow Mastiff': 'Теневой Мастифф',
    'Shoosuva': 'Шусува',
    'Slithering Tracker': 'Склизкий Преследователь',
    'Spawn Of Kyuss': 'Порождение Кьюсса',
    'Stegosaurus': 'Стегозавр',
    'Stench Kow (Cow)': 'Мускусный Бык (Корова)',
    'Stone Giant Dreamwalker': 'Каменный Гигант Сноходец',
    'Storm Giant Quintessent': 'Штормовой Гигант Квинтэссент',
    'Swarm Of Cranium Rats': 'Рой Черепных Крыс',
    'Swarm Of Rot Grubs': 'Рой Личинок Древоточцев',
    'Swashbuckler': 'Сорвиголова',
    'Tanarukk': 'Танарукк',
    'Thorny': 'Колючка',
    'Tlincaui': 'Тлинкалли',
    'Transmuter': 'Преобразователь',
    'Trapper': 'Траппер',
    'Ulitharid': 'Улитарид',
    'Vargouille': 'Варгулья',
    'Vegepygmy': 'Вегепигмей',
    'Vegepygmy Chief': 'Вегепигмей Вождь',
    'Velociraptor': 'Велоцираптор',
    'War Priest': 'Боевой Священник',
    'Warlock Of The Archfey': 'Колдун Архифеи',
    'Warlock Of The Fiend': 'Колдун Исчадия',
    'Warlock Of The Great Old One': 'Колдун Великого Древнего',
    'Warlord': 'Военачальник',
    'Wood Woad': 'Лесная Вайда',
    'Xvart': 'Ксварт',
    'Xvart Warlock Ofraxivort': 'Ксварт Колдун Раксиворта',
    'Yeth Hound': 'Гончая Йет',
    'Yuan-Ti Anathema': 'Юань-Ти Анафема',
    'Yuan-Ti Broodguard': 'Юань-Ти Страж Выводка',
    'Yuan-Ti Mind Whisperer': 'Юань-Ти Шепчущий В Мыслях',
    'Yuan-Ti Nightmare Speaker': 'Юань-Ти Говорящая В Кошмарах',
    'Yuan-Ti Pit Master': 'Юань-Ти Хозин Ямы',
    'Eye Tyran': 'Тираноглаз',
    'Beholder Hive': 'Улей',
    'Death Tyrant': 'Тиран Смерти',
}

tfyp_names_dict = {
    'Animated Table': 'Оживленный Стол',
    'Centaur Mummy': 'Мумия-Кентавр',
    'Choker': 'Душитель',
    'Deathlock Wight': 'Колдовское Умертвие',
    'Dread Warrior': 'Воин Ужаса',
    'Duergar Spy': 'Дуэргар-Шпион',
    'Giant Crayfish': 'Гигантский Рак',
    'Giant Ice Toad': 'Гигантская Ледяная Жаба',
    'Giant Lightning Eel': 'Гигантский Электрический Угорь',
    'Giant Skeleton': 'Гигантский Скелет',
    'Giant Subterranean Lizard': 'Гигантская Подземная Ящерица',
    'Greater Zombie': 'Усиленный Зомби',
    'Kalka-Kylla': 'Калка-Килла',
    'Kelpie': 'Келпи',
    'Malformed Kraken': 'Уродливый Кракен',
    'Nereid': 'Нереида',
    'Ooze Master': 'Повелитель Слизей',
    'Sea Lion': 'Морской Лев',
    'Sharwyn Hucrele': 'Шарвин Хукреле',
    'Sir Braford': 'Сэр Брэдфорд',
    'Siren': 'Сирена',
    'Tarul Var': 'Тарул Вар',
    'Tecuziztecatl': 'Текузизтекатль',
    'Thayan Apprentice': 'Тэйский Ученик Мага',
    'Thayan Warrior': 'Тэйский Воин',
    'Thorn Slinger': 'Метатель Шипов',
    'Vampiric Mist': 'Вампирический Туман',
    'White Maw': 'Белая Пасть',
    'Yusdrayl': 'Йусдрайл',
}

name_dict = {**common_name_dict, **volo_names_dict, **tfyp_names_dict}