# -*- coding:utf-8 -*-

common_name_dict = {
    "Wight": "Умертвие",
    "Spy": "Шпион",
    "Assassin": "Наёмный убийца",
    "Tecuziztecatl": "Текузизтекатль",
    "Sharwyn": "Шарвин",
    "The kraken": "Кракен",
    "Abjuration": "Ограждение",
    "Conjuration": "Вызов",
    "Divination": "Прорицание",
    "Enchantment": "Очарование",
    "Evocation": "Воплощение",
    "Illusion": "Иллюзия",
    "Necromancy": "Некромантия",
    "Transmutation": "Преобразование",
    "": "",
    "barbarian": "варвар",
    "bard": "бард",
    "cleric": "жрец",
    "druid": "друид",
    "fighter": "воин",
    "monk": "монах",
    "paladin": "паладиин",
    "ranger": "следопыт",
    "rogue": "плут",
    "sorcerer": "чародей",
    "warlock": "колдун",
    "wizard": "волшебник",
}

volo_names_dict = {
    'Abjurer': 'Оградитель',
    'Alhoon': 'Алхун',
    'Annis Hag': 'Карга Аннис',
    'Apprentice Wizard': 'Ученик волшебника',
    'Archdruid': 'Архидруид',
    'Archer': 'Лучник',
    'Aurochs': 'Тур',
    'Babau': 'Бабау',
    'Banderhobb': 'Бандерхобб',
    'Bard': 'Бард',
    'Barghest': 'Баргест',
    'Bheur Hag': 'Карга Бйор',
    'Blackguard': 'Тёмный страж',
    'Bodak': 'Бодак',
    'Boggle': 'Боггл',
    'Brontosaurus': 'Бронтозавр',
    'Catoblepas': 'Катоблепас',
    'Cave Fisher': 'Пещерный удильщик',
    'Champion': 'Чемпион',
    'Chitine': 'Хитин',
    'Choldrith': 'Холдрит',
    'Cloud Giant Smiling One': 'Облачный гигант Насмешник',
    'Conjurer': 'Призыватель',
    'Cow': 'Корова',
    'Cranium Rat': 'Черепная крыса',
    'Darkling': 'Дарклинг',
    'Darkling Elder': 'Старейшина дарклингов',
    'Death Kiss': 'Поцелуй Смерти',
    'Deep Scion': 'Глубинный отпрыск',
    'Deinonychus': 'Дейноних',
    'Devourer': 'Пожиратель',
    'Dimetrodon': 'Диметродон',
    'Diviner': 'Прорицатель',
    'Dolphin': 'Дельфин',
    'Draegloth': 'Дрэглот',
    'Elder Brain': 'Старший мозг',
    'Enchanter': 'Очарователь',
    'Evoker': 'Воплотитель',
    'Fire Giant Dreadnought': 'Огненный гигант Дредноут',
    'Firenewt': 'Огненный тритон',
    'Firenewt Warlock Of Lmix': 'Огненный тритон колдун Имикса',
    'Flail Snail': 'Цеповая улитка',
    'Flind': 'Флинд',
    'Froghemoth': 'Лягемот',
    'Frost Giant Everlasting One': 'Морозный гигант Извечный',
    'Gauth': 'Гаут',
    'Gazer': 'Зрящий',
    'Giant Strider': 'Гигантский ходун',
    'Girallon': 'Гираллон',
    'Gnoll Flesh Gnawer': 'Гнолл глодатель',
    'Gnoll Hunter': 'Гнолл охотник',
    'Gnoll Witherling': 'Иссохший гнолл',
    'Grung': 'Грунг',
    'Grung Elite Warrior': 'Элитный воин грунг',
    'Grung Wildling': 'Одичавший грунг',
    'Guard Drake': 'Сторожевой дрейк',
    'Hadrosaurus': 'Гадрозавр',
    'Hobgoblin Devastator': 'Хобгоблин-Опустошитель',
    'Hobgoblin Iron Shadow': 'Хобгоблин железная тень',
    'Illusionist': 'Иллюзионист',
    'Ki-Rin': 'Ки-Рин',
    'Kobold Dragonshield': 'Кобольд драконий щит',
    'Kobold Inventor': 'Кобольд изобретатель',
    'Kobold Scale Sorcerer': 'Кобольд чешуйчатый чародей',
    'Korred': 'Корред',
    'Kraken Priest': 'Священник кракена',
    'Leucrotta': 'Лекротта',
    'Martial Arts Adept': 'Адепт боевых искусств',
    'Master Thief': 'Мастер-вор',
    'Maw Demon': 'Утробный демон',
    'Meenlock': 'Минлок',
    'Mind Flayer Lich': 'Свежеватель разума лич',
    'Mindwitness': 'Свидетель разума',
    'Morkoth': 'Моркот',
    'Mouth Of Grolantor': 'Пасть Гролатора',
    'Necromancer': 'Некромант',
    'Neogi': 'Неоги',
    'Neogi Hatchling': 'Неоги личинка',
    'Neogi Master': 'Повелитель неоги',
    'Neothelid': 'Неотелид',
    'Nilbog': 'Нилбог',
    'Ore Blade Of Ilneval': 'Орк клинок Илневала',
    'Ore Claw Of Luthic': 'Орк коготь Лутик',
    'Ore Hand Ofyurtrus': 'Орк рука Юртруса',
    'Ore Nurtured One Ofyurtrus': 'Орк вскормленный Юртруса',
    'Ore Red Fang Of Shargaas': 'Орк красный клык Шаргааса',
    'Ox (Cow)': 'Як (корова)',
    'Quetzalcoatlus': 'Кетцалькоатль',
    'Quickling': 'Квиклинг',
    'Redcap': 'Красный колпак',
    'Rothe (Cow)': 'Роф (корова)',
    'Sea Spawn-': 'Морское отродье',
    'Shadow Mastiff': 'Теневой мастифф',
    'Shoosuva': 'Шусува',
    'Slithering Tracker': 'Склизкий преследователь',
    'Spawn Of Kyuss': 'Порождение Кьюсса',
    'Stegosaurus': 'Стегозавр',
    'Stench Kow (Cow)': 'Мускусный бык (корова)',
    'Stone Giant Dreamwalker': 'Каменный гигант Сноходец',
    'Storm Giant Quintessent': 'Штормовой гигант Квинтэссент',
    'Swarm Of Cranium Rats': 'Рой черепных крыс',
    'Swarm Of Rot Grubs': 'Рой личинок древоточцев',
    'Swashbuckler': 'Сорвиголова',
    'Tanarukk': 'Танарукк',
    'Thorny': 'Колючка',
    'Tlincaui': 'Тлинкалли',
    'Transmuter': 'Преобразователь',
    'Trapper': 'Траппер',
    'Ulitharid': 'Улитарид',
    'Vargouille': 'Варгулья',
    'Vegepygmy': 'Вегепигмей',
    'Vegepygmy Chief': 'Вегепигмей вождь',
    'Velociraptor': 'Велоцираптор',
    'War Priest': 'Боевой священник',
    'Warlock Of The Archfey': 'Колдун архифеи',
    'Warlock Of The Fiend': 'Колдун исчадия',
    'Warlock Of The Great Old One': 'Колдун великого древнего',
    'Warlord': 'Военачальник',
    'Wood Woad': 'Лесная вайда',
    'Xvart': 'Ксварт',
    'Xvart Warlock Raxivort': 'Ксварт колдун Раксиворта',
    'Yeth Hound': 'Гончая йет',
    'Yuan-Ti Anathema': 'Юань-ти анафема',
    'Yuan-Ti Broodguard': 'Юань-ти страж выводка',
    'Yuan-Ti Mind Whisperer': 'Юань-ти шепчущий в мыслях',
    'Yuan-Ti Nightmare Speaker': 'Юань-ти говорящая в кошмарах',
    'Yuan-Ti Pit Master': 'Юань-ти хозин ямы',
    'Eye Tyran': 'Тираноглаз',
    'Beholder Hive': 'Улей',
    'Death Tyrant': 'Тиран смерти',
}

tfyp_names_dict = {
    'Animated Table': 'Оживленный стол',
    'Centaur Mummy': 'Мумия-кентавр',
    'Choker': 'Душитель',
    'Deathlock Wight': 'Колдовское умертвие',
    'Dread Warrior': 'Воин ужаса',
    'Duergar Spy': 'Дуэргар-шпион',
    'Giant Crayfish': 'Гигантский рак',
    'Giant Ice Toad': 'Гигантская ледяная жаба',
    'Giant Lightning Eel': 'Гигантский электрический угорь',
    'Giant Skeleton': 'Гигантский скелет',
    'Giant Subterranean Lizard': 'Гигантская подземная ящерица',
    'Greater Zombie': 'Усиленный зомби',
    'Kalka-Kylla': 'Калка-килла',
    'Kelpie': 'Келпи',
    'Malformed Kraken': 'Уродливый кракен',
    'Nereid': 'Нереида',
    'Ooze Master': 'Повелитель слизей',
    'Sea Lion': 'Морской лев',
    'Sharwyn Hucrele': 'Шарвин хукреле',
    'Sir Braford': 'Сэр Брэдфорд',
    'Siren': 'Сирена',
    'Tarul Var': 'Тарул Вар',
    'Tecuziztecatl': 'Текузизтекатль',
    'Thayan Apprentice': 'Тэйский ученик мага',
    'Thayan Warrior': 'Тэйский воин',
    'Thorn Slinger': 'Метатель шипов',
    'Vampiric Mist': 'Вампирический туман',
    'White Maw': 'Белая пасть',
    'Yusdrayl': 'Йусдрайл',
}

name_dict = {**common_name_dict, **volo_names_dict, **tfyp_names_dict}