#-*- coding:utf-8 -*-

phb_spell = {
    "Acid splash": "Брызги кислоты",
    "Aid": "Подмога",
    "Alarm": "Сигнал тревоги",
    "Alter self": "Смена обличья",
    "Animal friendship": "Дружба с животными",
    "Animal messenger": "Почтовое животное",
    "Animal shapes": "Превращение в животных",
    "Animate dead": "Восставший труп",
    "Animate objects": "Оживление вещей",
    "Antilife shell": "Преграда жизни",
    "Antimagic field": "Преграда магии",
    "Antipathy/sympathy": "Антипатия/симпатия",
    "Arcane eye": "Магический глаз",
    "Arcane gate": "Магические врата",
    "Arcane lock": "Волшебный замок",
    "Armor of Agathys": "Доспех Агатиса",
    "Arms of Hadar": "Руки Хадара",
    "Astral projection": "Проекция в астрал",
    "Augury": "Гадание",
    "Aura of life": "Аура жизни",
    "Aura of purity": "Аура очищения",
    "Aura of vitality": "Аура живучести",
    "Awaken": "Пробуждение разума",
    "Bane": "Порча",
    "Banishing smite": "Изгоняющая кара",
    "Banishment": "Изгнание",
    "Barkskin": "Дубовая кора",
    "Beacon of hope": "Маяк надежды",
    "Beast sense": "Животные чувства",
    "Bestow curse": "Проклятие",
    "Bigby’s hand": "Длань Бигби",
    "Blade barrier": "Стена клинков",
    "Blade ward": "Защита от оружия",
    "Bless": "Благословение",
    "Blight": "Усыхание",
    "Blinding smite": "Ослепляющая кара",
    "Blindness/deafness": "Глухота/слепота",
    "Blink": "Мерцание",
    "Blur": "Размытый образ",
    "Branding smite": "Клеймящая кара",
    "Burning hands": "Огненные ладони",
    "Call lightning": "Призыв молнии",
    "Calm emotions": "Умиротворение",
    "Chain lightning": "Цепная молния",
    "Charm person": "Очарование личности",
    "Chill touch": "Леденящее прикосновение",
    "Chromatic orb": "Цветной шарик",
    "Circle of death": "Круг смерти",
    "Circle of power": "Круг силы",
    "Clairvoyance": "Ясновидение",
    "Clone": "Двойник",
    "Cloud of daggers": "Облако кинжалов",
    "Cloudkill": "Облако смерти",
    "Color spray": "Сверкающие брызги",
    "Command": "Приказ",
    "Commune": "Общение",
    "Commune with nature": "Общение с природой",
    "Compelled duel": "Вызов на дуэль",
    "Comprehend languages": "Понимание языков",
    "Compulsion": "Принуждение",
    "Cone of cold": "Конус холода",
    "Confusion": "Смятение",
    "Conjure animals": "Призыв животных",
    "Conjure barrage": "Призыв заграждения",
    "Conjure celestial": "Призыв небожителя",
    "Conjure elemental": "Призыв элементаля",
    "Conjure fey": "Призыв феи",
    "Conjure minor elementals": "Призыв малых элементалей",
    "Conjure volley": "Призыв залпа",
    "Conjure woodland beings": "Призыв лесных обитателей",
    "Contact other plane": "Связь с иным миром",
    "Contagion": "Заражение",
    "Contingency": "Предосторожность",
    "Continual flame": "Вечный огонь",
    "Control water": "Власть над водами",
    "Control weather": "Власть над погодой",
    "Cordon of arrows": "Завеса стрел",
    "Counterspell": "Контрзаклинание",
    "Create food and water": "Сотворение пищи и воды",
    "Create or destroy water": "Сотворение или уничтожение воды",
    "Create undead": "Сотворение нежити",
    "Creation": "Сотворение",
    "Crown of madness": "Корона безумия",
    "Crusader's mantle": "Мантия крестоносца",
    "Crusaders mantle": "Мантия крестоносца",
    "Cure wounds": "Лечение ран",
    "Dancing lights": "Пляшущие огоньки",
    "Darkness": "Тьма",
    "Darkvision": "Тёмное зрение",
    "Daylight": "Дневной свет",
    "Death ward": "Защита от смерти",
    "Delayed blast fireball": "Замедленный огненный шар",
    "Demiplane": "Демиплан",
    "Destructive wave": "Разрушительная волна",
    "Detect evil and good": "Обнаружение добра и зла",
    "Detect magic": "Обнаружение магии",
    "Detect poison and disease": "Обнаружение болезней и яда",
    "Detect thoughts": "Обнаружение мыслей",
    "Dimension door": "Переносящая дверь",
    "Disguise self": "Маскировка",
    "Disintegrate": "Распад",
    "Dispel evil and good": "Рассеивание добра и зла",
    "Dispel magic": "Рассеивание магии",
    "Dissonant whisper": "Диссонирующий шёпот",
    "Divination": "Предсказание",
    "Divine favor": "Божественное благоволение",
    "Divine word": "Божественное слово",
    "Dominate beast": "Подчинение зверя",
    "Dominate monster": "Подчинение чудовища",
    "Dominate person": "Подчинение личности",
    "Drawmij’s instant summons": "Дромиджево появление ",
    "Drawmijs instant summons": "Дромиджево появление ",
    "Dream": "Вещий сон",
    "Druidcraft": "Искусство друидов",
    "Earthquake": "Землетрясение",
    "Eldritch blast": "Мистический заряд",
    "Elemental weapon": "Стихийное оружие",
    "Enhance ability": "Улучшение характеристики",
    "Enlarge/reduce": "Увеличение/уменьшение",
    "Ensnaring strike": "Опутывающий удар",
    "Entangle": "Опутывание",
    "Enthrall": "Речь златоуста",
    "Etherealness": "Эфирность",
    "Evard's black tentackles": "Эвардовы чёрные щупальца",
    "Evards black tentackles": "Эвардовы чёрные щупальца",
    "Evards black tentacles": "Эвардовы чёрные щупальца",
    "Expeditious retreat": "Поспешное отступление",
    "Eyebite": "Разящее око",
    "Fabricate": "Изготовление",
    "Faerie fire": "Огонь фей",
    "False life": "Псевдожизнь",
    "Fear": "Ужас",
    "Feather fall": "Падение пёрышком",
    "Feeblemind": "Слабоумие",
    "Feign death": "Притворная смерть",
    "Find familiar": "Поиск фамильяра",
    "Find steed": "Поиск скакуна",
    "Find the path": "Поиск пути",
    "Find traps": "Поиск ловушек",
    "Finger of death": "Перст смерти",
    "Fire bolt": "Огненный снаряд",
    "Fire shield": "Огненный щит",
    "Fire storm": "Огненная буря",
    "Fireball": "Огненный шар",
    "Flame blade": "Горящий клинок",
    "Flame strike": "Небесный огонь",
    "Flaming sphere": "Пылающий шар",
    "Flesh to stone": "Окаменение",
    "Fly": "Полёт",
    "Fog cloud": "Туманное облако",
    "Forbiddance": "Запрет",
    "Forcecage": "Узилище",
    "Foresight": "Предвидение",
    "Freedom of movement": "Свобода перемещения",
    "Friends": "Дружба",
    "Gaseous form": "Газообразная форма",
    "Gate": "Врата",
    "Geas": "Обет",
    "Gentle repose": "Нетленные останки",
    "Giant insect": "Гигантское насекомое",
    "Glibness": "Находчивость",
    "Globe of invulnerability": "Сфера неуязвимости",
    "Glyph of warding": "Охранные руны",
    "Goodberry": "Чудо-ягоды",
    "Grasping vine": "Цепкая лоза",
    "Grease": "Скольжение",
    "Greater invisibility": "Высшая невидимость",
    "Greater restoration": "Высшее восстановление",
    "Guardian of faith": "Страж веры",
    "Guards and wards": "Стражи",
    "Guidance": "Указание",
    "Guiding bolt": "Направленный снаряд",
    "Gust of wind": "Порыв ветра",
    "Hail of thorns": "Град шипов",
    "Hallow": "Святилище",
    "Hallucinatory terrain": "Мираж",
    "Harm": "Поражение",
    "Haste": "Ускорение",
    "Heal": "Полное исцеление",
    "Healing word": "Лечащее слово",
    "Heat metal": "Раскалённый металл",
    "Hellish rebuke": "Адское возмездие",
    "Heroes’ feast": "Пир героев",
    "Heroism": "Героизм",
    "Hex": "Сглаз",
    "Hold monster": "Удержание чудовища",
    "Hold person": "Удержание личности",
    "Holy aura": "Аура святости",
    "Hunger of Hadar": "Голод Хадара",
    "Hunter's mark": "Метка охотника",
    "Hunters mark": "Метка охотника",
    "Hypnotic pattern": "Гипнотический узор",
    "Ice storm": "Град",
    "Identify": "Опознание",
    "Illusory script": "Невидимое письмо",
    "Imprisonment": "Заточение",
    "Incendiary cloud": "Воспламеняющаяся туча",
    "Inflict wounds": "Нанесение ран",
    "Insect plague": "Нашествие насекомых",
    "Invisibility": "Невидимость",
    "Jump": "Прыжок",
    "Knock": "Открывание",
    "Legend lore": "Знание легенд",
    "Leomund’s secret chest": "Леомундов потайной сундук",
    "Leomund’s tiny hut": "Леомундова хижина",
    "Lesser restoration": "Малое восстановление",
    "Levitate": "Левитация",
    "Light": "Свет",
    "Lightning arrow": "Молниевая стрела",
    "Lightning bolt": "Молния",
    "Locate animals or plants": "Поиск животных или растений",
    "Locate creature": "Поиск существа",
    "Locate object": "Поиск предмета",
    "Longstrider": "Скороход",
    "Mage armor": "Доспехи мага",
    "Mage hand": "Волшебная рука",
    "Magic circle": "Магический круг",
    "Magic jar": "Волшебный сосуд",
    "Magic missile": "Волшебная стрела",
    "Magic mouth": "Волшебные уста",
    "Magic weapon": "Магическое оружие",
    "Major image": "Образ",
    "Mass cure wounds": "Множественное лечение ран",
    "Mass heal": "Множественное полное исцеление",
    "Mass healing word": "Множественное лечащее слово",
    "Mass suggestion": "Множественное внушение",
    "Maze": "Лабиринт",
    "Meld into stone": "Слияние с камнем",
    "Melf's acid arrow": "Мельфова кислотная стрела",
    "Melfs acid arrow": "Мельфова кислотная стрела",
    "Mending": "Починка",
    "Message": "Сообщение",
    "Meteor swarm": "Метеоритный дождь",
    "Mind blank": "Сокрытие разума",
    "Minor illusion": "Малая иллюзия",
    "Mirage arcane": "Таинственный мираж",
    "Mirror image": "Отражения",
    "Mislead": "Фальшивый двойник",
    "Misty step": "Туманный шаг",
    "Modify memory": "Изменение памяти",
    "Moonbeam": "Лунный луч",
    "Mordenkainen’s faithful hound": "Верный пёс Морденкайнена",
    "Mordenkainen’s magnificent mansion": "Великолепный особняк Морденкайнена",
    "Mordenkainen’s private sanctum": "Кабинет Морденкайнена",
    "Mordenkainen’s sword": "Меч Морденкайнена",
    "Move earth": "Движение почвы",
    "Nondetection": "Необнаружимость",
    "Nystul’s magic aura": "Нистулова ложная аура",
    "Otiluke’s freezing sphere": "Отилюков ледяной шар",
    "Otiluke’s resilient sphere": "Отилюков упругий шар",
    "Otto’s irresistible dance": "Неудержимая пляска Отто",
    "Pass without trace": "Бесследное передвижение",
    "Passwall": "Создание прохода",
    "Phantasmal force": "Воображаемая сила",
    "Phantasmal killer": "Воображаемый убийца",
    "Phantom steed": "Прирачный скакун",
    "Planar ally": "Планарный союзник",
    "Planar binding": "Планарные узы",
    "Plane shift": "Уход в иной мир",
    "Plant growth": "Рост растений",
    "Poison spray": "Ядовитые брызги",
    "Polymorph": "Превращение",
    "Power word heal": "Слово Силы: исцеление",
    "Power word kill": "Слово Силы: смерть",
    "Power word stun": "Слово Силы: оглушение",
    "Prayer of healing": "Молебен лечения",
    "Prestidigitation": "Фокусы",
    "Prismatic spray": "Радужные брызги",
    "Prismatic wall": "Радужная стена",
    "Produce flame": "Сотворение пламени",
    "Programmed illusion": "Заданная иллюзия",
    "Project image": "Проекция",
    "Protection from energy": "Защита от энергии",
    "Protection from evil and good": "Защита от добра и зла",
    "Protection from poison": "Защита от яда",
    "Purify food and drink": "Очищение пищи и питья",
    "Raise dead": "Оживление",
    "Rary’s telepathic bond": "Ментальная связь Рэри",
    "Ray of enfeeblement": "Луч слабости",
    "Ray of frost": "Луч холода",
    "Ray of sickness": "Луч болезни",
    "Regenerate": "Регенерация",
    "Reincarnate": "Реинкарнация",
    "Remove curse": "Снятие проклятья",
    "Resistance": "Сопротивление",
    "Resurrection": "Воскрешение",
    "Reverse gravity": "Изменение тяготения",
    "Revivify": "Возрождение",
    "Rope trick": "Трюк с верёвкой",
    "Sacred flame": "Священное пламя",
    "Sanctuary": "Убежище",
    "Scorching ray": "Палящий луч",
    "Scrying": "Наблюдение",
    "Searing smite": "Палящая кара",
    "See invisibility": "Видение невидимого",
    "Seeming": "Притворство",
    "Sending": "Послание",
    "Sequester": "Изоляция",
    "Shapechange": "Полное превращение",
    "Shatter": "Дребезги",
    "Shield": "Щит",
    "Shield of faith": "Щит веры",
    "Shillelagh": "Дубинка",
    "Shocking grasp": "Электрошок",
    "Silence": "Тишина",
    "Silent image": "Безмолвный образ",
    "Simulacrum": "Подобие",
    "Sleep": "Усыпление",
    "Sleet storm": "Метель",
    "Slow": "Замедление",
    "Spare the dying": "Уход за умирающим",
    "Speak with animals": "Разговор с животными",
    "Speak with dead": "Разговор с мёртвыми",
    "Speak with plants": "Разговор с растениями",
    "Spider climb": "Паучье лазание",
    "Spider Climb": "Паучье лазание",
    "Spike growth": "Шипы",
    "Spirit guardians": "Духовные стражи",
    "Spiritual weapon": "Божественное оружие",
    "Staggering smite": "Оглушающая кара",
    "Stinking cloud": "Зловонное облако",
    "Stone shape": "Изменение формы камня",
    "Stoneskin": "Каменная кожа",
    "Storm of vengeance": "Гроза гнева",
    "Suggestion": "Внушение",
    "Sunbeam": "Солнечный луч",
    "Sunburst": "Солнечный ожог",
    "Swift quiver": "Быстрый колчан",
    "Symbol": "Знак",
    "Tasha's hideous laughter": "Жуткий смех Таши",
    "Tashas hideous laughter": "Жуткий смех Таши",
    "Telekinesis": "Телекинез",
    "Telepathy": "Телепатия",
    "Teleport": "Телепортация",
    "Teleportation circle": "Круг телепортации",
    "Tenser’s floating disk": "Тензеров парящий диск",
    "Thaumaturgy": "Чудотворство",
    "Thorn whip": "Терновый кнут",
    "Thunderous smite": "Громовая кара",
    "Thunderwave": "Волна грома",
    "Time stop": "Остановка времени",
    "Tongues": "Языки",
    "Transport via plants": "Путешествие через растения",
    "Tree stride": "Древесный путь",
    "True polymorph": "Истинное превращение",
    "True resurrection": "Истинное воскрешение",
    "True seeing": "Истинное зрение",
    "True strike": "Меткий удар",
    "Tsunami": "Цунами",
    "Unseen servant": "Невидимый слуга",
    "Vampiric touch": "Прикосновение вампира",
    "Vicious mockery": "Злая насмешка",
    "Wall of fire": "Огненная стена",
    "Wall of force": "Силовая стена",
    "Wall of ice": "Ледяная стена",
    "Wall of stone": "Каменная стена",
    "Wall of thorns": "Терновая стена",
    "Warding bond": "Охраняющая связь",
    "Water breathing": "Подводное дыхание",
    "Water walk": "Хождение по воде",
    "Web": "Паутина",
    "Weird": "Смертный ужас",
    "Wind walk": "Хождение по ветру",
    "Wind wall": "Стена ветров",
    "Wish": "Исполнение желаний",
    "Witch bolt": "Ведьмин снаряд",
    "Word of recall": "Слово возврата",
    "Wrathful smite": "Гневная кара",
    "Zone of truth": "Область истины",
}

ee_spell = {
    "Abi-Dalzim's Horrid Wilting": "Ужасное увядание Аби-Далзима",
    "Abi-Dalzims Horrid Wilting": "Ужасное увядание Аби-Далзима",
    "Absorb Elements": "Поглощение стихий",
    "Aganazzar's Scorcher": "Пекло Аганаззара",
    "Aganazzars Scorcher": "Пекло Аганаззара",
    "Beast Bond": "Звериные узы",
    "Bones of the Earth": "Кости земли",
    "Catapult": "Катапульта",
    "Control Flames": "Власть над огнём",
    "Control Winds": "Власть над ветрами",
    "Create Bonfire": "Сотворение костра",
    "Dust Devil": "Пылевой вихрь",
    "Earth Tremor": "Дрожь земли",
    "Earthbind": "Узы земли",
    "Elemental Bane": "Проклятье стихий",
    "Erupting Earth": "Извержение земли",
    "Flame Arrows": "Пылающие стрелы",
    "Frostbite": "Обморожение",
    "Gust": "Шквал",
    "Ice Knife": "Ледяной кинжал",
    "Immolation": "Испепеление",
    "Investiture of Flame": "Облачение огня",
    "Investiture of Ice": "Облачение льда",
    "Investiture of Stone": "Облачение камня",
    "Investiture of Wind": "Облачение ветра",
    "Maelstrom": "Водоворот",
    "Magic Stone": "Волшебный камень",
    "Maximilian's Earthen Grasp": "Земляная хватка Максимилиана",
    "Maximilians Earthen Grasp": "Земляная хватка Максимилиана",
    "Melf's Minute Meteors": "Мельфовы маленькие метеоры",
    "Melfs Minute Meteors": "Мельфовы маленькие метеоры",
    "Mold Earth": "Лепка земли",
    "Primordial Ward": "Первородный страж",
    "Pyrotechnics": "Пиротехника",
    "Shape Water": "Формование воды",
    "Skywrite": "Небесные письмена",
    "Snilloc's Snowball Swarm": "Снежный шквал Сниллока",
    "Snillocs Snowball Swarm": "Снежный шквал Сниллока",
    "Storm Sphere": "Сфера бури",
    "Thunderclap": "Раскат грома",
    "Tidal Wave": "Приливная волна",
    "Transmute Rock": "Преобразование камня",
    "Vitriolic Sphere": "Едкий шар",
    "Wall of Sand": "Песчаная стена",
    "Wall of Water": "Водяная стена",
    "Warding Wind": "Защитный ветер",
    "Watery Sphere": "Водяная сфера",
    "Whirlwind": "Смерч",
}

scag_spell = {
    "Booming Blade": "Громовый Клинок",
    "Green-Flame Blade": "Клинок Зеленого Пламени",
    "Lightning Lure": "Лассо Молнии",
    "Sword Burst": "Вспышка Мечей",
}

tfyp_spell = {
    "Crave Bolt": "Снаряд желания",
    "": "",
}

xanatar_dict = {
    "Abi-Dalzim's horrid wilting": "Ужасное увядание Аби-Далзима",
    "Abi-Dalzims horrid wilting": "Ужасное увядание Аби-Далзима",
    "Absorb elements": "Поглощение стихий",
    "Aganazzar's scorcher": "Пекло Аганаззара",
    "Aganazzars scorcher": "Пекло Аганаззара",
    "Beast bond": "Звериные узы",
    "Bones of the earth": "Кости земли",
    "Catapult": "Катапульта",
    "Catnap": "Дрёма",
    "Cause fear": "Вызов страха",
    "Ceremony": "Церемония",
    "Chaos bolt": "заряд хаоса",
    "Charm monster": "Очарование монстра",
    "Control flames": "Власть над огнём",
    "Control winds": "Власть над ветрами",
    "Create bonfire": "Сотворение костра",
    "Create homunculus": "Сотворения гоммункула",
    "Crown of stars": "Корона Звезд",
    "Danse macabre": "Пляска смерти",
    "Dawn": "Восход",
    "Dragon's breath": "дыхание дракона",
    "Druid grove": "друидская роща",
    "Dust devil": "Пылевой вихрь",
    "Earth tremor": "Дрожь земли",
    "Earthbind": "Узы земли",
    "Elemental bane": "Проклятье стихий",
    "Enemies abound": "изобилие врагов",
    "Enervation": "Обессиливание",
    "Erupting earth": "Извержение земли",
    "Far step": "Далекий шаг",
    "Find greater steed": "Поиск высшего скакуна",
    "Flame arrow": "Пылающая стрела",
    "Frostbite": "Обморожение",
    "Guardian of nature": "Страж природы",
    "Gust": "Шквал",
    "Healing spirit": "Исцеляющий дух",
    "Holy weapon": "Святое оружие",
    "Ice knife": "Ледяной кинжал",
    "Illusory dragon": "Иллюзорный дракон",
    "Immolation": "Испепеление",
    "Infernal calling": "Инфернальный зов",
    "Infestation": "Нашествие",
    "Investiture of flame": "Облачение огня",
    "Investiture of ice": "Облачение льда",
    "Investiture of stone": "Облачение камня",
    "Investiture of wind": "Облачение ветра",
    "Invulnerability": "Неуязвимость",
    "Life transference": "Передача жизни",
    "Maddening darkness": "Одуряющая тьма",
    "Maelstrom": "Водоворот",
    "Magic stone": "Волшебный камень",
    "Mass polymorph": "Множественное превращение",
    "Maximilian's earthen grasp": "Земляная хватка Максимилиана",
    "Maximilians earthen grasp": "Земляная хватка Максимилиана",
    "Melf's minute meteors": "Мельфовы маленькие метеоры",
    "Melfs minute meteors": "Мельфовы маленькие метеоры",
    "Mental prison": "Ментальная тюрьма",
    "Mighty fortress": "Могучая крепость",
    "Mind spike": "Пронзание разума",
    "Mold earth": "Лепка земли",
    "Negative energy flood": "Потоп негативной энергии",
    "Power word pain": "Слово силы боль",
    "Primal savagery": "Первобытная дикость",
    "Primordial ward": "Первородный страж",
    "Psychic scream": "Психический крик",
    "Pyrotechnics": "Пиротехника",
    "Scatter": "Рассеивание",
    "Shadow blade": "Теневой клинок",
    "Shadow of moil": "Облачение тени",
    "Shape water": "Формование воды",
    "Sickening radiance": "Болезненное сияние",
    "Skill empowerment": "Усиление навыка",
    "Skywrite": "Небесные письмена",
    "Snare": "Силок",
    "Snilloc’s snowball swarm": "Снежный шквал Сниллока",
    "Soul cage": "Клетка душ",
    "Steel wind strike": "Удар стального ветра",
    "Storm sphere": "Сфера бури",
    "Summon greater demon": "Призыв высшего демона",
    "Summon lesser demons": "Призыв низших демонов",
    "Synaptic static": "Синаптический разряд",
    "Temple of the gods": "Храм богов",
    "Tenser's transformation": "Трансформация Тензера",
    "Tensers transformation": "Трансформация Тензера",
    "Thunder step": "Громовой шаг",
    "Thunderclap": "Раскат грома",
    "Tidal wave": "Приливная волна",
    "Tiny servant": "Крошечный слуга",
    "Toll the dead": "Звон по мертвым",
    "Transmute rock": "Преобразование камня",
    "Vitriolic sphere": "Едкий шар",
    "Wall of light": "Стена света",
    "Wall of sand": "Песчаная стена",
    "Wall of water": "Водяная стена",
    "Warding wind": "Защитный ветер",
    "Watery sphere": "Водяная сфера",
    "Whirlwind": "Смерч",
    "Word of radiance": "Слово сияния",
    "Wrath of nature": "Гнев природы ",
    "Zephyr strike": "Удар Зефира",
    "Bountiful Luck": "Бездонная удача",
    "Dragon Fear": "Драконий страх",
    "Dragon Hide": "Драконья шкура",
    "Drow High Magic": "Высшая магия дроу",
    "Dwarven Fortitude": "Дварфийская стойкость",
    "Elven Accuracy": "Эльфийская точность",
    "Fade Away": "Исчезновение",
    "Fey Teleportation": "Телепортация фей",
    "Flames of Phlegethos": "Пламя Флегетоса",
    "Infernal Constitution": "Инфернальное телосложение",
    "Squat Nimbleness": "Низкорослое проворство",
    "Orcish Fury": "Орочье буйство",
    "Prodigy": "Вундеркинд",
    "Second Chance": "второй шанс",
    "Wood Elf Magic": "магия лесных эльфов",
    "Aspect of the Moon": "Аспект луны",
    "Cloak of Flies": "плащ мух",
    "Eldritch Smite": "Мистическая кара",
    "Ghostly Gaze": "призрачный взор",
    "Gift of the Depths": "дар глубин",
    "Gift of the Ever-Living Ones": "Дар вечноживых",
    "Grasp of Hadar": "Хватка Хадара",
    "Improved Pact Weapon": "Улучшенное оружие договора",
    "Lance of Lethargy": "Копье Летаргии",
    "Maddening Hex": "Безумное проклятие",
    "Relentless Hex": "Безжалостное проклятие",
    "Shroud of Shadow": "саван теней",
    "Tomb of Levistus": "Гробница Левитуса",
    "Trickster's Escape": "Побег обманщика",
}

spell_dict = {**phb_spell, **ee_spell, **scag_spell, **tfyp_spell, **xanatar_dict}

